#!/bin/sh

/usr/bin/getent group stunnel || /usr/sbin/groupadd -g 48 stunnel
/usr/bin/getent passwd stunnel || /usr/sbin/useradd -g stunnel -u 48 \
	-d /var/run/stunnel -s /bin/false stunnel

/usr/bin/passwd -l stunnel

/bin/chown stunnel:stunnel /var/run/stunnel

# End of file.
