#!/bin/sh

getent group mysql  || /usr/sbin/groupadd -g 46 mysql
getent passwd mysql || /usr/sbin/useradd -g mysql -u 46 \
	-d /var/lib/mysql -s /bin/false mysql

/usr/bin/passwd -l mysql

/bin/chown mysql:mysql /var/{{lib,log,run}/mysql,lib/mysql-files}

# End of file.
